/*
  SORU HAVUZU
  -----------
  Her grup (minik / muhafiz) yaklaşık yarı yarıya "tarim" ve "doga" sorusu içerir.
  Oyun her seferinde 5 soruyu rastgele, tipleri ve konuları dengeleyerek seçer.

  Ortak alanlar:
    id    : benzersiz kısa ad
    lv    : zorluk seviyesi — 1: 7–8 yaş · 2: 9–10 yaş · 3: 11–13 yaş · 4: 14 yaş ve üstü
            (oyun, oyuncunun yaşına uyan seviyeden soru seçer; yetmezse komşu seviyeden tamamlar)
    cat   : "tarim" | "doga"
    type  : "choice" | "truefalse" | "silhouette" | "map"
    q     : soru metni
    fact  : "Biliyor muydunuz?" kutusunda gösterilen bilgi

  Tiplere göre:
    choice / silhouette : options: [{ t: "Metin", i: "görsel" }], answer: doğru seçeneğin sırası (0'dan başlar)
    truefalse           : answer: true | false
    silhouette          : art: siluete dönüşecek görsel (seçeneklerde görsel kullanmayın, cevabı ele verir)
    map                 : item: sürüklenecek görsel, label: adı, cities: haritadaki şehirler, answer: doğru şehir anahtarı
                          (şehir anahtarları js/art.js > CITIES içinde)

  Görsel yazımı: emoji ("🐝"), özel çizim ("svg:kelaynak", "svg:ceylan", "svg:pamuk", "svg:fistik", "svg:pati", "svg:bugday")
                 veya koyulaştırılmış emoji ("dark:🌹" – karagül için).
*/
window.QUESTIONS = {
  minik: [
    // ---------- TARIM ----------
    { id: "m-isot", lv: 2, cat: "tarim", type: "map", photo: "isot", q: "Acı biber İSOT hangi şehrimizin meşhur ürünüdür? Biberi o şehre sürükle!",
      item: "🌶️", label: "İsot", cities: ["sanliurfa", "rize", "izmir", "ankara", "van", "antalya"], answer: "sanliurfa",
      fact: "İsot, Şanlıurfa'da gündüz güneşte kurutulur, gece örtülerek 'terletilir'. Koyu rengi ve tatlımsı acılığı buradan gelir." },
    { id: "m-cay", lv: 2, cat: "tarim", type: "map", photo: "cay", q: "Çay en çok hangi şehrimizde yetişir? Çay yaprağını oraya sürükle!",
      item: "🍃", label: "Çay", cities: ["rize", "sanliurfa", "konya", "izmir", "antalya", "van"], answer: "rize",
      fact: "Çay bitkisi bol yağmur sever. Karadeniz'in yağmurlu yamaçları, özellikle Rize, Türkiye'nin çay bahçesidir." },
    { id: "m-findik", lv: 2, cat: "tarim", type: "map", photo: "findik", q: "Fındığı Karadeniz'deki fındık şehrimize sürükle!",
      item: "svg:findik", label: "Fındık", cities: ["giresun", "konya", "sanliurfa", "izmir", "van", "adana"], answer: "giresun",
      fact: "Dünyadaki fındığın yarıdan fazlası Türkiye'de, çoğu da Karadeniz kıyılarında yetişir." },
    { id: "m-fistik", lv: 2, cat: "tarim", type: "map", photo: "antep-fistigi", q: "Adını bir şehrimizden alan bu fıstığı doğru şehre sürükle!",
      item: "svg:fistik", label: "Antep Fıstığı", cities: ["gaziantep", "rize", "izmir", "samsun", "edirne", "van"], answer: "gaziantep",
      fact: "Antep fıstığı coğrafi işaretli bir üründür. Gaziantep ve Şanlıurfa, fıstığın en çok yetiştiği illerimizdendir." },
    { id: "m-bal", lv: 1, cat: "tarim", type: "choice", q: "Hangisi bal yapar?",
      options: [{ t: "Arı", i: "🐝", p: "bal-arisi" }, { t: "Kelebek", i: "🦋", p: "kelebek" }, { t: "Uğur böceği", i: "🐞", p: "ugur-bocegi" }], answer: 0,
      fact: "Arılar çiçeklerden topladıkları nektarı bala dönüştürür. Yarım kilo bal için yaklaşık 2 milyon çiçeği ziyaret ederler!" },
    { id: "m-ari-ses", lv: 1, cat: "tarim", type: "silhouette", photo: "bal-arisi", q: "Bu siluet hangi hayvana ait? Vızz vızz diye uçar!",
      art: "🐝", options: [{ t: "Arı" }, { t: "Kuş" }, { t: "Balık" }], answer: 0,
      fact: "Arılar çiçek tozlarını çiçekten çiçeğe taşıyarak birçok meyve ve sebzenin oluşmasına yardım eder. Buna tozlaşma denir." },
    { id: "m-bitki-ihtiyac", lv: 1, cat: "tarim", type: "truefalse", photo: "filiz", q: "Bitkilerin büyümek için suya, ışığa ve havaya ihtiyacı vardır.", answer: true,
      fact: "Bitkiler güneş ışığını kullanarak kendi besinlerini üretir. Buna fotosentez denir." },
    { id: "m-pamuk", lv: 2, cat: "tarim", type: "silhouette", photo: "pamuk", q: "Bu siluet, Harran Ovası'nda çok yetişen ve 'beyaz altın' denen hangi bitkiye ait?",
      art: "svg:pamuk", options: [{ t: "Pamuk" }, { t: "Mısır" }, { t: "Karpuz" }], answer: 0,
      fact: "Tişört, çorap ve havlular pamuktan yapılır. Şanlıurfa, Türkiye'de en çok pamuk üreten ilimizdir." },
    { id: "m-bugday", lv: 1, cat: "tarim", type: "silhouette", photo: "bugday", q: "Ekmeğimizi yapan bu bitki hangisi?",
      art: "svg:bugday", options: [{ t: "Buğday" }, { t: "Çilek" }, { t: "Domates" }], answer: 0,
      fact: "Bilim insanlarına göre ilk buğdaylardan biri olan siyez, binlerce yıl önce Şanlıurfa yakınlarındaki Karacadağ çevresinde tarlaya ekilmeye başlandı." },
    { id: "m-havuc", lv: 1, cat: "tarim", type: "choice", q: "Hangisi toprağın altında yetişir?",
      options: [{ t: "Havuç", i: "🥕", p: "havuc" }, { t: "Elma", i: "🍎", p: "elma" }, { t: "Kiraz", i: "🍒", p: "kiraz" }], answer: 0,
      fact: "Havuç, patates ve soğan gibi sebzeler toprağın altında büyür." },
    { id: "m-solucan", lv: 1, cat: "tarim", type: "truefalse", photo: "solucan", q: "Solucanlar toprağa zarar verir.", answer: false,
      fact: "Solucanlar toprağı havalandırır ve verimli hâle getirir. Onlar çiftçinin gizli yardımcılarıdır!" },
    { id: "m-genbank", lv: 1, cat: "tarim", type: "choice", q: "Tohumları uzun yıllar güvenle saklayan yere ne denir?",
      options: [{ t: "Tohum Gen Bankası", i: "🏦" }, { t: "Kütüphane", i: "📚" }, { t: "Hastane", i: "🏥" }], answer: 0,
      fact: "Türkiye Tohum Gen Bankası Ankara'dadır ve TAGEM'e bağlıdır. Burada binlerce bitkinin tohumu soğukta saklanır." },
    { id: "m-sut", lv: 1, cat: "tarim", type: "choice", q: "İnekten hangisini elde ederiz?",
      options: [{ t: "Süt", i: "🥛", p: "sut" }, { t: "Bal", i: "🍯", p: "bal" }, { t: "Yumurta", i: "🥚", p: "yumurta" }], answer: 0,
      fact: "Sütten peynir, yoğurt ve ayran yapılır. Ayran en sevilen içeceklerimizdendir!" },

    // ---------- DOĞA ----------
    { id: "m-kelaynak", lv: 2, cat: "doga", type: "choice", q: "Birecik'te koruma altında olan ve göç eden ünlü kuş hangisi?",
      options: [{ t: "Penguen", i: "🐧", p: "penguen" }, { t: "Kelaynak", i: "svg:kelaynak", p: "kelaynak" }, { t: "Papağan", i: "🦜", p: "papagan" }], answer: 1,
      fact: "Kelaynağın başında tüy yoktur, bu yüzden 'kel' denir. Dünyanın en nadir kuşlarından biridir ve Birecik'te korunur." },
    { id: "m-karagul", lv: 2, cat: "doga", type: "choice", q: "Halfeti'de koyu, neredeyse siyah renkte açan gülün adı nedir?",
      options: [{ t: "Kırmızı Gül", i: "🌹" }, { t: "Karagül", i: "dark:🌹" }, { t: "Lale", i: "🌷" }], answer: 1,
      fact: "Karagül, Halfeti'nin gün ışığı, sıcaklığı ve kireçli toprağı sayesinde koyu renkte açar. Başka yere dikilince kırmızı ya da mor açar!" },
    { id: "m-guguk", lv: 3, cat: "doga", type: "truefalse", photo: "guguk-kusu", q: "Guguk kuşu yumurtalarını başka kuşların yuvasına bırakır.", answer: true,
      fact: "Guguk kuşu yumurtalarını başka kuşların yuvasına bırakır. Yavrularını o kuşlar büyütür!" },
    { id: "m-kurbaga", lv: 1, cat: "doga", type: "choice", q: "Hem suda hem karada yaşayabilen hayvan hangisi?",
      options: [{ t: "Kurbağa", i: "🐸", p: "kurbaga" }, { t: "Arı", i: "🐝", p: "bal-arisi" }, { t: "Kedi", i: "🐱", p: "kedi" }], answer: 0,
      fact: "Kurbağalar hem suda hem karada yaşar ve zararlı böcekleri yiyerek doğaya yardım eder." },
    { id: "m-pars", lv: 2, cat: "doga", type: "silhouette", photo: "anadolu-parsi", q: "Bu siluet, neslinin tükendiği sanılan hangi hayvanımıza ait?",
      art: "🐆", options: [{ t: "Anadolu Parsı" }, { t: "Ayı" }, { t: "Kurt" }], answer: 0,
      fact: "Anadolu parsının yok olduğu sanılıyordu. Son yıllarda fotokapanlarla görüntülenmesi, ülkemizde hâlâ yaşadığını gösterdi!" },
    { id: "m-ceylan", lv: 2, cat: "doga", type: "silhouette", photo: "ceylan", q: "Şanlıurfa'nın ovalarında koruma altında yaşayan bu zarif hayvan hangisi?",
      art: "svg:ceylan", options: [{ t: "Ceylan" }, { t: "Tavşan" }, { t: "Tilki" }], answer: 0,
      fact: "Şanlıurfa'daki Ceylanpınar'da Türkiye'nin en büyük Asya ceylanı sürüsü koruma altında. Sürü, 23 ceylandan bugün yaklaşık bine ulaştı!" },
    { id: "m-firat-tatli", lv: 2, cat: "doga", type: "truefalse", photo: "firat-kaplumbagasi", q: "Fırat kaplumbağasının kabuğu yumuşaktır.", answer: true,
      fact: "Fırat kaplumbağasının kabuğu yumuşaktır. Başının ucundaki küçük hortumu şnorkel gibi su yüzüne çıkarıp nefes alır. Nesli tehlike altındadır." },
    { id: "m-kelaynak-harita", lv: 2, cat: "doga", type: "map", photo: "kelaynak", q: "Kelaynağı yaşadığı şehre sürükle!",
      item: "svg:kelaynak", label: "Kelaynak", cities: ["sanliurfa", "istanbul", "izmir", "trabzon", "erzurum", "antalya"], answer: "sanliurfa",
      fact: "Kelaynaklar Şanlıurfa'nın Birecik ilçesinde, Fırat Nehri kıyısındaki kayalıklarda yaşar." },
    { id: "m-geri-donusum", lv: 1, cat: "doga", type: "choice", q: "Doğayı korumak için hangisini yapmalıyız?",
      options: [{ t: "Çöpleri geri dönüştürmek", i: "♻️" }, { t: "Ormanda ateş yakmak", i: "🔥" }, { t: "Çöpü yere atmak", i: "🥫" }], answer: 0,
      fact: "Bir cam şişe doğada binlerce yıl bozulmadan kalabilir. Geri dönüşüm doğayı korur." },
    { id: "m-penguen", lv: 1, cat: "doga", type: "truefalse", photo: "penguen", q: "Penguenler Türkiye'nin ormanlarında yaşar.", answer: false,
      fact: "Penguenlerin neredeyse hepsi güney yarımkürede yaşar ve çoğu soğuk denizleri sever. Türkiye'de ise kelaynak, flamingo ve leylek gibi pek çok kuş vardır." },
    { id: "m-yuva", lv: 1, cat: "doga", type: "choice", q: "Bir kuş yuvası görürsek ne yapmalıyız?",
      options: [{ t: "Uzaktan izlemek", i: "👀" }, { t: "Yumurtaları almak", i: "🥚" }, { t: "Yuvayı indirmek", i: "✋" }], answer: 0,
      fact: "Kuşların yuvasını bozmak, yumurtalarını ya da yavrularını almak yasaktır. Yuvaya yaklaşmak kuşları korkutup rahatsız eder; doğayı uzaktan izlemek en iyisidir." },
    { id: "m-pati", lv: 2, cat: "doga", type: "silhouette", typeLabel: "İzleri takip et", photo: "anadolu-parsi", q: "Bu ayak izi hangi hayvana ait olabilir?",
      art: "svg:pati", options: [{ t: "Anadolu Parsı" }, { t: "Kelaynak" }, { t: "Ceylan" }], answer: 0,
      fact: "Anadolu parsı bir kedigildir; kedigillerin izinde tırnak genellikle görünmez. Kuşların izi ince çizgiler, ceylanınki ise ikiye ayrık toynak şeklindedir." },
    // ---------- SEVİYE 1 (7–8 yaş) ek sorular ----------
    { id: "k-agac", lv: 1, cat: "tarim", type: "choice", q: "Hangisi ağaçta yetişir?",
      options: [{ t: "Elma", i: "🍎", p: "elma" }, { t: "Havuç", i: "🥕", p: "havuc" }, { t: "Patates", i: "🥔", p: "patates" }], answer: 0,
      fact: "Elma ağaçta yetişir. Havuç ve patates ise toprağın altında büyür." },
    { id: "k-tavuk", lv: 1, cat: "tarim", type: "choice", q: "Tavuklar bize hangisini verir?",
      options: [{ t: "Yumurta", i: "🥚", p: "yumurta" }, { t: "Süt", i: "🥛", p: "sut" }, { t: "Bal", i: "🍯", p: "bal" }], answer: 0,
      fact: "Tavuklar yumurta verir. Sütü inek, koyun ve keçi; balı ise arılar verir." },
    { id: "k-ucan", lv: 1, cat: "doga", type: "choice", q: "Hangisi uçabilir?",
      options: [{ t: "Baykuş", i: "🦉", p: "baykus" }, { t: "Kurbağa", i: "🐸", p: "kurbaga" }, { t: "Kedi", i: "🐱", p: "kedi" }], answer: 0,
      fact: "Baykuşlar geceleri avlanır. Tarla farelerini yiyerek çiftçiye yardım ederler." },
    { id: "k-tohum", lv: 1, cat: "tarim", type: "choice", photo: "filiz", q: "Toprağa ekilip sulanan tohumdan ne çıkar?",
      options: [{ t: "Filiz", i: "🌱" }, { t: "Civciv", i: "🐣" }, { t: "Top", i: "⚽" }], answer: 0,
      fact: "Tohum toprağa ekilip sulanınca filizlenir. Filiz büyüyüp bitki olur." },
    { id: "k-kelebek", lv: 1, cat: "doga", type: "choice", q: "Hangisi çiçekten çiçeğe uçar?",
      options: [{ t: "Kelebek", i: "🦋", p: "kelebek" }, { t: "Solucan", i: "🐛", p: "solucan" }, { t: "Kurbağa", i: "🐸", p: "kurbaga" }], answer: 0,
      fact: "Kelebeklerin çoğu, çiçeklerin içindeki nektar denen tatlı suyu içerek beslenir. Çiçekten çiçeğe uçarken çiçek tozlarını taşıyarak bitkilerin meyve ve tohum vermesine yardım ederler." },
    { id: "k-canli", lv: 1, cat: "tarim", type: "truefalse", photo: "filiz", q: "Bitkiler de canlıdır; büyür ve gelişir.", answer: true,
      fact: "Bitkiler canlıdır. Su, ışık ve havayla beslenerek büyürler." },
    { id: "k-kus-yumurta", lv: 1, cat: "doga", type: "truefalse", photo: "guvercin", q: "Kuşlar yumurtadan çıkar.", answer: true,
      fact: "Bütün kuşlar yumurtadan çıkar. Güvercinlerde anne ve baba sırayla yumurtaların üstüne oturup onları sıcak tutar." },
    { id: "k-balik", lv: 1, cat: "doga", type: "truefalse", photo: "inci-kefali", q: "Balıklar ağaçta yaşar.", answer: false,
      fact: "Balıklar suda yaşar. Solungaçlarıyla suyun içindeki oksijeni alırlar." },
    { id: "k-kaplumbaga", lv: 1, cat: "doga", type: "silhouette", photo: "firat-kaplumbagasi", q: "Bu siluet, sırtında kabuğunu taşıyan hangi hayvana ait?",
      art: "🐢", options: [{ t: "Kaplumbağa" }, { t: "Tavşan" }, { t: "Kedi" }], answer: 0,
      fact: "Fırat Nehri'nde yaşayan Fırat kaplumbağasının kabuğu yumuşaktır!" },
    { id: "k-inek", lv: 1, cat: "tarim", type: "silhouette", q: "Bize süt veren bu hayvan hangisi?",
      art: "🐄", options: [{ t: "İnek" }, { t: "At" }, { t: "Köpek" }], answer: 0,
      fact: "İnekler bize süt verir. Sütten peynir, yoğurt ve ayran yapılır." },
    { id: "k-kelaynak-harita", lv: 1, cat: "doga", type: "map", photo: "kelaynak", q: "Kelaynak Şanlıurfa'da yaşar. Kuşu haritada Şanlıurfa yazan yere taşı!",
      item: "svg:kelaynak", label: "Kelaynak", cities: ["sanliurfa", "istanbul", "ankara"], answer: "sanliurfa",
      fact: "Kelaynaklar Şanlıurfa'nın Birecik ilçesinde, Fırat Nehri kıyısında yaşar." },
    { id: "k-cay-harita", lv: 1, cat: "tarim", type: "map", photo: "cay", q: "Çay en çok Rize'de yetişir. Çay yaprağını haritada Rize yazan yere taşı!",
      item: "🍃", label: "Çay", cities: ["rize", "antalya", "sanliurfa"], answer: "rize",
      fact: "Çay bitkisi bol yağmur sever. Rize'nin yağmurlu yamaçlarında çok çay yetişir." },

    // ---------- SEVİYE 2 (9–10 yaş) ek sorular ----------
    { id: "k-domates", lv: 2, cat: "tarim", type: "truefalse", q: "Domates, bitkinin çiçeğinden oluşur.", answer: true,
      fact: "Domates bitkisinin sarı çiçekleri tozlaşınca, çiçeğin ortasındaki küçük kısım büyüyerek domatese dönüşür. Seralarda bombus arıları çiçekleri titreterek bu tozlaşmaya yardım eder." },
    { id: "k-ceylan-otcul", lv: 2, cat: "doga", type: "truefalse", photo: "ceylan", q: "Ceylanlar et yiyen yırtıcı hayvanlardır.", answer: false,
      fact: "Ceylanlar ot yiyen (otçul) hayvanlardır. Hızlı koşarak kendilerini yırtıcılardan korurlar." },

    // ---------- YENİ SORULAR (v2.7) ----------
    { id: "n-fistik-yesil-ic", lv: 1, cat: "tarim", type: "choice", q: "Şanlıurfa'da çok yetişen, içi yeşil olan kuruyemiş hangisi?",
      options: [{ t: "Fındık", p: "findik" }, { t: "Antep fıstığı", p: "antep-fistigi" }, { t: "Kayısı", p: "kayisi" }], answer: 1,
      fact: "Antep fıstığı ağaçlarının erkeği ve dişisi ayrıdır; fıstığı dişi ağaç verir. Çiçek tozlarını erkek ağaçtan dişi ağaca rüzgâr taşır." },
    { id: "n-ugur-bocegi-dost", lv: 1, cat: "tarim", type: "choice", q: "Hangisi bitkilere zarar veren küçük böcekleri yiyerek çiftçiye yardım eder?",
      options: [{ t: "Sivrisinek", i: "🦟", p: "sivrisinek" }, { t: "Karasinek", p: "karasinek" }, { t: "Uğur böceği", i: "🐞", p: "ugur-bocegi" }], answer: 2,
      fact: "Bir uğur böceği bir günde onlarca yaprak biti yiyebilir. Adana'daki TAGEM'e bağlı Biyolojik Mücadele Araştırma Enstitüsü, zararlılara karşı böyle faydalı canlıları araştırır." },
    { id: "n-bozayi-kis-ini", lv: 1, cat: "doga", type: "choice", q: "Hangisi kışı ininde uyuyarak geçirir?",
      options: [{ t: "Bozayı", i: "🐻", p: "bozayi" }, { t: "Horoz", i: "🐓", p: "horoz" }, { t: "Kedi", i: "🐱", p: "kedi" }], answer: 0,
      fact: "Bozayılar sonbaharda bol bol yiyip yağ depolar, kış uykusunda hiç yemek yemez. Yavruları da kışın ininde doğar! Ülkemizde ormanlık dağlarda yaşarlar." },
    { id: "n-karpuz-agac", lv: 1, cat: "tarim", type: "truefalse", q: "Karpuz ağaçta yetişir.", answer: false,
      fact: "Karpuz, toprağın üstüne yayılarak büyüyen bir bitkide yetişir. Meyvesinin yaklaşık yüzde 92'si sudur!" },
    { id: "n-harran-keleri-siluet", lv: 1, cat: "doga", type: "silhouette", photo: "e-harrankeleri", q: "Bu siluet, Şanlıurfa'nın Harran ilçesinde yaşayan küçük bir hayvana ait. Hangisi?",
      art: "🦎", options: [{ t: "Kurbağa" }, { t: "Kertenkele" }, { t: "Kaplumbağa" }], answer: 1,
      fact: "Bu kertenkelenin adı Harran yaprakparmaklı keleri. Dünyada yalnızca ülkemizde yaşar ve bilim dünyasına 2011'de Harran'dan tanıtıldı." },
    { id: "n-elma-isparta-harita", lv: 1, cat: "tarim", type: "map", photo: "elma", q: "Elma en çok Isparta'da yetişir. Elmayı haritada Isparta yazan yere taşı!",
      item: "🍎", label: "Elma", cities: ["isparta", "rize", "sanliurfa"], answer: "isparta",
      fact: "Eğirdir'deki TAGEM'e bağlı Meyvecilik Araştırma Enstitüsü, çiçekleri bahar soğuklarında donmasın diye geç çiçek açan yeni elma çeşitleri geliştiriyor." },
    { id: "n-sulama-saati", lv: 2, cat: "tarim", type: "choice", q: "Yaz günü bahçeyi ne zaman sularsak suyun daha azı buharlaşıp boşa gider?",
      options: [{ t: "Öğle sıcağında", i: "☀️" }, { t: "Sabah erkenden", i: "🌅" }, { t: "Rüzgârlı öğleden sonra", i: "🌬️" }], answer: 1,
      fact: "Sıcak ve rüzgâr suyun buharlaşmasını hızlandırır. Sabah sulanan bitkinin yaprakları gün içinde kurur; akşam sulananlar ise gece ıslak kalıp mantar hastalığına açık olur." },
    { id: "n-pamuk-cigit", lv: 2, cat: "tarim", type: "choice", q: "Harran Ovası'nda çok yetişen pamuğun tohumundan (çiğit) hangisi elde edilir?",
      options: [{ t: "Yün", i: "🧶" }, { t: "Şeker", i: "🍬" }, { t: "Yemeklik yağ", i: "🍳" }], answer: 2,
      fact: "Pamuğun lifinden kumaş dokunur. Yağı alınan tohumun geri kalanı (küspe) de boşa gitmez; hayvanlara yem olur." },
    { id: "n-gobeklitepe-hayvan", lv: 2, cat: "doga", type: "choice", q: "Şanlıurfa'daki Göbeklitepe'nin dikili taşlarında hangileri oyulmuştur?",
      options: [{ t: "Arabalar", i: "🚗" }, { t: "Yabani hayvanlar", i: "🦊" }, { t: "Harfler ve yazılar", i: "🔤" }], answer: 1,
      fact: "Taşlarda en çok yılan, tilki, yaban domuzu ve akbaba gibi kuşların kabartmaları var. Bu taşlar, yazı icat edilmeden binlerce yıl önce oyuldu!" },
    { id: "n-yer-fistigi", lv: 2, cat: "tarim", type: "truefalse", q: "Yer fıstığı, dalda değil toprağın altında oluşur.", answer: true,
      fact: "Yer fıstığının çiçeği tozlaşınca sapı uzayıp toprağa gömülür; fıstık orada büyür. Osmaniye yer fıstığı coğrafi işaretli bir ürünümüzdür." },
    { id: "n-orumcek-bacak", lv: 2, cat: "doga", type: "truefalse", q: "Örümcekler 6 bacaklı birer böcektir.", answer: false,
      fact: "Örümceklerin 8 bacağı vardır; böcek değil, 'örümceğimsiler' denen ayrı bir gruptandırlar. Birçoğu ağıyla sinek ve sivrisinek yakalayarak doğal dengeye yardım eder." },
    { id: "n-ivesi-siluet", lv: 2, cat: "tarim", type: "silhouette", q: "Bu siluet, Şanlıurfa'da çok yetiştirilen, sütü bol İvesi ırkına ait. Hangi hayvan?",
      art: "🐑", options: [{ t: "Keçi" }, { t: "İnek" }, { t: "Koyun" }], answer: 2,
      fact: "Şanlıurfa'daki TAGEM'e bağlı GAP Tarımsal Araştırma Enstitüsü, çiftçilerle birlikte en iyi hayvanları seçip çoğaltarak İvesi koyunlarının süt verimini artırdı." },
    { id: "n-kirpi-siluet", lv: 2, cat: "doga", type: "silhouette", q: "Bu siluet, geceleri bahçelerde böcek ve salyangoz avlayan hangi hayvana ait?",
      art: "🦔", options: [{ t: "Kirpi" }, { t: "Sincap" }, { t: "Tavşan" }], answer: 0,
      fact: "Kirpi tehlike anında top gibi kıvrılır ve dikenleriyle korunur. Sümüklü böcek ve zararlı böcekleri yediği için bahçelerin doğal bekçisidir." },
    { id: "n-karpuz-harita", lv: 2, cat: "tarim", type: "map", q: "Dev karpuzlarıyla ünlü ilimiz hangisi? Karpuzu o ile sürükle!",
      item: "🍉", label: "Karpuz", cities: ["diyarbakir", "rize", "erzurum", "istanbul", "edirne", "van"], answer: "diyarbakir",
      fact: "Diyarbakır karpuzu coğrafi işaretli bir ürünümüzdür. Eski 'kuyu karpuzculuğu' yöntemiyle 50 kilogramı aşan dev karpuzlar bile yetiştirilebilir!" },
    // ---------- YENİ SORULAR (v3.2) ----------
    { id: "v3-patates", lv: 1, cat: "tarim", type: "choice", q: "Hangisi meyve değil, bir sebzedir?",
      options: [{ t: "Patates", p: "patates" }, { t: "Kiraz", p: "kiraz" }, { t: "Elma", p: "elma" }], answer: 0,
      fact: "Patatesin yediğimiz kısmı kök değil, toprağın altında büyüyen şişkin bir gövdedir. Üzerindeki 'gözlerden' yeni patates filizleri çıkar!" },
    { id: "v3-cita", lv: 1, cat: "doga", type: "choice", q: "Hangisi en hızlı koşan kara hayvanıdır?",
      options: [{ t: "Çita", p: "cita" }, { t: "Kaplumbağa", i: "🐢" }, { t: "Salyangoz", i: "🐌" }], answer: 0,
      fact: "Çita kısa bir mesafede saatte 100 kilometreden hızlı koşabilir, ama bu hızı ancak birkaç yüz metre sürdürebilir. Esnek omurgası ona yay gibi sıçrama gücü verir." },
    { id: "v3-bicerdover", lv: 1, cat: "tarim", type: "choice", photo: "bugday", q: "Tarladaki olgun buğdayı biçip tanelerini ayıran makinenin adı nedir?",
      options: [{ t: "Biçerdöver", i: "🌾" }, { t: "İtfaiye aracı", i: "🚒" }, { t: "Vinç", i: "🏗️" }], answer: 0,
      fact: "Biçerdöver hem biçer hem döver; adı da buradan gelir. Eskiden bu iş için haftalarca orak sallanır, harman dövülürdü!" },
    { id: "v3-agac-oksijen", lv: 1, cat: "doga", type: "truefalse", q: "Ağaçlar yapraklarıyla oksijen üretir.", answer: true,
      fact: "Yapraklar güneş ışığıyla besin yaparken havadaki karbondioksiti alır, oksijen verir. Buna fotosentez denir." },
    { id: "v3-kus-goc", lv: 1, cat: "doga", type: "truefalse", q: "Bazı kuşlar kış gelmeden sıcak ülkelere göç eder.", answer: true,
      fact: "Leylekler her sonbahar Afrika'ya uçar, baharda eski yuvalarına geri döner. Onların göç yolu ülkemizin üzerinden geçer!" },
    { id: "v3-peynir", lv: 1, cat: "tarim", type: "truefalse", photo: "sut", q: "Peynir sütten yapılır.", answer: true,
      fact: "1 kilogram peynir için yaklaşık 6-10 litre süt gerekir. Ülkemizde inek, koyun, keçi ve manda sütünden yüzlerce çeşit peynir yapılır." },
    { id: "v3-aycicegi-siluet", lv: 1, cat: "tarim", type: "silhouette", q: "Bu siluet, tohumlarından yağ yapılan, kocaman sarı çiçekli bitkiye ait. Hangisi?",
      art: "🌻", options: [{ t: "Lale" }, { t: "Ayçiçeği" }, { t: "Papatya" }], answer: 1,
      fact: "Genç ayçiçekleri gün boyu güneşi izler; olgunlaşınca başları doğuya dönük kalır. Ülkemizde ayçiçeği en çok Trakya'da yetişir." },
    { id: "v3-sincap-siluet", lv: 1, cat: "doga", type: "silhouette", q: "Bu siluet, kabarık kuyruklu, ağaçta yaşayan ve kışa ceviz saklayan hangi hayvana ait?",
      art: "🐿️", options: [{ t: "Tavşan" }, { t: "Sincap" }, { t: "Fare" }], answer: 1,
      fact: "Sincaplar kış için toprağa ceviz ve fındık gömer. Bulamadıkları tohumlar filizlenip ağaca dönüşür; yani sincaplar orman diker!" },
    { id: "v3-van-kedisi-harita", lv: 1, cat: "doga", type: "map", q: "Van kedisi Van'da yaşar. Kediyi haritada Van yazan yere taşı!",
      item: "🐈", label: "Van Kedisi", cities: ["van", "isparta", "edirne"], answer: "van",
      fact: "Van kedilerinin bazılarının bir gözü mavi, öbürü sarı ya da yeşildir. Birçok kedinin aksine suyu sever ve yüzebilir!" },
    { id: "v3-pamuk-harita", lv: 1, cat: "tarim", type: "map", photo: "pamuk", q: "Pamuk en çok Şanlıurfa'da yetişir. Pamuğu haritada Şanlıurfa yazan yere taşı!",
      item: "svg:pamuk", label: "Pamuk", cities: ["sanliurfa", "samsun", "izmir"], answer: "sanliurfa",
      fact: "Pamuk çiçeğinden sonra 'koza' oluşur. Koza olgunlaşınca açılır ve içinden bembeyaz lifler çıkar. Tişörtlerimiz bu liflerden yapılır!" },
    { id: "v3-bugday-konya-harita", lv: 2, cat: "tarim", type: "map", photo: "bugday", q: "'Türkiye'nin tahıl ambarı' denen, buğdayın en çok yetiştiği ilimize buğdayı sürükle!",
      item: "svg:bugday", label: "Buğday", cities: ["konya", "rize", "van", "izmir", "samsun", "antalya"], answer: "konya",
      fact: "Konya'daki TAGEM'e bağlı Bahri Dağdaş Uluslararası Tarımsal Araştırma Enstitüsü, kuraklığa dayanıklı yeni buğday çeşitleri geliştirir." },
    { id: "v3-kestane-harita", lv: 2, cat: "tarim", type: "map", q: "Kestane şekeriyle ünlü ilimize kestaneyi sürükle!",
      item: "🌰", label: "Kestane", cities: ["bursa", "sanliurfa", "erzurum", "adana", "van", "samsun"], answer: "bursa",
      fact: "Bursa kestane şekeri coğrafi işaretli bir lezzetimizdir. Kestane ağaçları yüzlerce yıl yaşayabilir; çiçekleri de arılar için önemli bir bal kaynağıdır." },
    { id: "v3-kartal-siluet", lv: 2, cat: "doga", type: "silhouette", q: "Bu siluet, çok yüksekten avını görebilen, keskin gözlü hangi kuşa ait?",
      art: "🦅", options: [{ t: "Kartal" }, { t: "Tavuk" }, { t: "Penguen" }], answer: 0,
      fact: "Kartalların gözleri insanınkinden kat kat keskindir; çok uzaktaki bir tavşanı bile fark edebilirler. Ülkemizde şah kartal ve kaya kartalı koruma altındadır." },
    { id: "v3-manda-siluet", lv: 2, cat: "tarim", type: "silhouette", q: "Bu siluet, suda ve çamurda serinlemeyi seven, sütünden kaymak yapılan hangi hayvana ait?",
      art: "🐃", options: [{ t: "At" }, { t: "Manda" }, { t: "Deve" }], answer: 1,
      fact: "Manda sütü çok yağlıdır; ünlü Afyon kaymağı manda sütünden yapılır. TAGEM, Anadolu mandası gibi yerli hayvan ırklarımızın korunmasını destekler." },
    { id: "v3-yilan", lv: 2, cat: "doga", type: "truefalse", q: "Ülkemizde yaşayan yılanların hepsi zehirlidir.", answer: false,
      fact: "Ülkemizdeki yılanların çoğu zehirsizdir ve fare yiyerek tarlalara yardım eder. Yine de zehirli olanı ayırt etmek zordur: yılana asla dokunma, uzaktan izle!" },
    { id: "v3-kabakgiller", lv: 2, cat: "tarim", type: "truefalse", q: "Kabak, salatalık ve karpuz aynı bitki ailesindendir.", answer: true,
      fact: "Hepsi 'kabakgiller' ailesindendir. Bu bitkiler toprağın üstüne yayılarak ya da tutunup tırmanarak büyür; çiçeklerini çoğunlukla arılar tozlaştırır." },
    { id: "v3-domates-amerika", lv: 2, cat: "tarim", type: "truefalse", q: "Domates, dünyaya Amerika kıtasından yayılmıştır.", answer: true,
      fact: "Domates, patates, mısır ve biber Amerika'dan geldi. Buğday, mercimek ve nohut ise Güneydoğu Anadolu'nun da içinde olduğu Bereketli Hilal'de tarıma alındı!" },
    { id: "v3-iribas", lv: 2, cat: "doga", type: "choice", photo: "kurbaga", q: "Kurbağa yavrularına ne ad verilir?",
      options: [{ t: "İribaş", i: "💧" }, { t: "Kuzu", i: "🐑" }, { t: "Civciv", i: "🐤" }], answer: 0,
      fact: "İribaşlar suda yaşar ve balık gibi solungaçla nefes alır. Büyüdükçe önce arka, sonra ön bacakları çıkar, kuyrukları kaybolur ve kurbağaya dönüşürler." },
    { id: "v3-orman-yangini", lv: 2, cat: "doga", type: "choice", q: "Ülkemizde orman yangınlarının çoğu neden çıkar?",
      options: [{ t: "İnsanların dikkatsizliği", i: "🔥" }, { t: "Yağmur", i: "🌧️" }, { t: "Kar", i: "❄️" }], answer: 0,
      fact: "Söndürülmeden bırakılan mangal ateşi ya da atılan bir sigara koca bir ormanı yakabilir. Orman yangını görürsen hemen 112'yi ara!" },
    { id: "v3-mercimek", lv: 2, cat: "tarim", type: "choice", q: "Hangisi baklagiller ailesindendir?",
      options: [{ t: "Mercimek", i: "🥣" }, { t: "Mısır", p: "misir" }, { t: "Elma", p: "elma" }], answer: 0,
      fact: "Mercimek, nohut ve fasulye baklagildir. Kırmızı mercimek ülkemizde en çok Şanlıurfa'da yetişir. Mercimek, Bereketli Hilal'de ilk tarıma alınan bitkilerdendir." },
    { id: "v3-kizil-tilki", lv: 2, cat: "doga", type: "choice", q: "Hangisi ülkemizin doğasında yaşayan yabani bir hayvandır?",
      options: [{ t: "Puma", p: "puma" }, { t: "Kızıl tilki", p: "kizil-tilki" }, { t: "Penguen", p: "penguen" }], answer: 1,
      fact: "Kızıl tilki ülkemizin hemen her yerinde yaşar ve tarla faresi avlayarak doğal dengeye yardım eder. Göbeklitepe'nin taşlarında da tilki kabartmaları var!" }
  ],

  muhafiz: [
    // ---------- TARIM ----------
    { id: "g-siyez", lv: 4, cat: "tarim", type: "choice", q: "Göbeklitepe yakınlarındaki Karacadağ, hangi bitkinin ilk tarıma alındığı yerlerden biri olarak bilinir?",
      options: [{ t: "Siyez (einkorn) buğdayı", i: "🌾", p: "siyez" }, { t: "Mısır", i: "🌽", p: "misir" }, { t: "Patates", i: "🥔", p: "patates" }], answer: 0,
      fact: "Genetik araştırmalar, siyez buğdayının yaklaşık 10 bin yıl önce Karacadağ çevresinde ilk kez tarıma alındığını gösteriyor. Mısır ve patates ise Amerika kökenlidir." },
    { id: "g-ataturk-baraji", lv: 3, cat: "tarim", type: "choice", q: "Fırat'ın suyu, Şanlıurfa Tünelleri ile hangi barajdan Harran Ovası'na taşınır?",
      options: [{ t: "Atatürk Barajı", i: "🏞️" }, { t: "Keban Barajı", i: "🌊" }, { t: "Ilısu Barajı", i: "💧" }], answer: 0,
      fact: "Atatürk Barajı Türkiye'nin en büyük barajıdır. Suyu tünellerle Harran Ovası'na ulaşır ve ovayı bereketli bir tarım alanına çevirmiştir." },
    { id: "g-gap", lv: 3, cat: "tarim", type: "choice", q: "GAP kısaltmasının açılımı nedir?",
      options: [{ t: "Güneydoğu Anadolu Projesi", i: "🗺️" }, { t: "Genel Araştırma Programı", i: "🔬" }, { t: "Gıda ve Arıcılık Planı", i: "🍯" }], answer: 0,
      fact: "GAP; baraj, sulama, enerji ve tarımı kapsayan, Türkiye'nin en büyük bölgesel kalkınma projelerinden biridir." },
    { id: "g-damla", lv: 3, cat: "tarim", type: "truefalse", photo: "damla-sulama", q: "Damla sulama, salma (vahşi) sulamaya göre daha fazla su harcar.", answer: false,
      fact: "Damla sulama suyu doğrudan bitki köküne verir; salma sulamaya göre çok daha az su harcar ve toprağın tuzlanmasını azaltır." },
    { id: "g-genbank", lv: 3, cat: "tarim", type: "choice", q: "Tohum gen bankalarında tohumlar onlarca yıl canlı kalabilmek için nasıl saklanır?",
      options: [{ t: "Kurutulup donma altı sıcaklıkta", i: "❄️" }, { t: "Güneş altında", i: "☀️" }, { t: "Su dolu kaplarda", i: "💧" }], answer: 0,
      fact: "Türkiye Tohum Gen Bankası (TAGEM, Ankara), tohumları kurutup yaklaşık –18 °C'de saklar. Bu, gelecek nesiller için bir 'tohum sigortası'dır." },
    { id: "g-sensor", lv: 3, cat: "tarim", type: "choice", q: "Akıllı tarımda toprağa yerleştirilen sensörler çiftçiye hangi bilgiyi anlık verir?",
      options: [{ t: "Toprak nemi ve sıcaklığı", i: "📡" }, { t: "Kuşların göç rotası", i: "🧭" }, { t: "Yakıt fiyatları", i: "⛽" }], answer: 0,
      fact: "Sensör verisiyle bitki tam ihtiyaç duyduğunda sulanır; su, enerji ve gübre tasarrufu sağlanır." },
    { id: "g-ari-ses", lv: 2, cat: "tarim", type: "choice", q: "Çiçek tozlarını taşıyarak meyvelerin oluşmasına en çok yardım eden böcek hangisi?",
      options: [{ t: "Bal arısı", i: "🐝", p: "bal-arisi" }, { t: "Sivrisinek", i: "🦟", p: "sivrisinek" }, { t: "Karasinek", i: "", p: "karasinek" }], answer: 0,
      fact: "Dünyadaki önemli gıda bitkisi türlerinin yaklaşık dörtte üçü, en azından kısmen, arılar gibi tozlaştırıcılara bağlıdır." },
    { id: "g-baykus", lv: 2, cat: "tarim", type: "choice", q: "Tarla farelerini avlayarak çiftçiye doğal yoldan yardım eden gece kuşu hangisi?",
      options: [{ t: "Baykuş", i: "🦉", p: "baykus" }, { t: "Horoz", i: "🐓", p: "horoz" }, { t: "Güvercin", i: "🕊️", p: "guvercin" }], answer: 0,
      fact: "Bir baykuş ailesi bir yılda binlerce kemirgen avlayabilir. Bu, ilaçsız 'biyolojik mücadele'nin güzel bir örneğidir." },
    { id: "g-gul", lv: 3, cat: "tarim", type: "map", photo: "yag-gulu", q: "Gül yağıyla dünyaca ünlü ilimize gülü sürükle!",
      item: "🌹", label: "Yağ Gülü", cities: ["isparta", "rize", "van", "samsun", "sanliurfa", "erzurum"], answer: "isparta",
      fact: "Isparta'nın yağ gülünden elde edilen gül yağı dünyanın en değerli bitkisel yağlarındandır. 1 kg gül yağı için tonlarca gül yaprağı gerekir." },
    { id: "g-kayisi", lv: 3, cat: "tarim", type: "map", photo: "kayisi", q: "Kayısıyı, 'dünyanın kayısı başkenti' denen ilimize sürükle!",
      item: "🍑", label: "Kayısı", cities: ["malatya", "rize", "edirne", "izmir", "van", "samsun"], answer: "malatya",
      fact: "Malatya kayısısı coğrafi işaretlidir; dünyadaki kuru kayısının büyük bölümü Malatya'dan çıkar." },
    { id: "g-tiftik", lv: 4, cat: "tarim", type: "map", photo: "tiftik-kecisi", q: "Tiftik keçisi dünyaya hangi ilimizin adıyla yayılmıştır? Keçiyi oraya sürükle!",
      item: "🐐", label: "Tiftik Keçisi", cities: ["ankara", "antalya", "trabzon", "sanliurfa", "izmir", "van"], answer: "ankara",
      fact: "Tiftik keçisinin parlak, ipeksi lifine 'tiftik' (moher) denir. Dünyada 'Angora keçisi' olarak tanınır." },
    { id: "g-ata-tohum", lv: 4, cat: "tarim", type: "truefalse", photo: "yerel-tohum", q: "Yerel (ata) tohumlar, yetiştikleri bölgenin iklimine ve hastalıklarına uyum sağlamıştır.", answer: true,
      fact: "Yerel çeşitler yüzyıllar içinde bölgelerine uyum sağlamıştır. Bu genetik zenginlik, yeni ve dayanıklı çeşitler geliştirmek için kullanılır." },
    { id: "g-toprak", lv: 3, cat: "tarim", type: "choice", q: "1 cm verimli toprağın doğada oluşması yaklaşık ne kadar sürebilir?",
      options: [{ t: "Yüzlerce yıl", i: "⏳" }, { t: "Bir hafta", i: "📅" }, { t: "Bir ay", i: "🗓️" }], answer: 0,
      fact: "Toprak çok yavaş oluşur ama erozyonla tek bir sağanakta kaybolabilir. Ağaçlandırma ve doğru toprak işleme erozyonu önler." },

    // ---------- DOĞA ----------
    { id: "g-pars", lv: 3, cat: "doga", type: "choice", q: "Neslinin tükendiği sanılan ama son yıllarda Türkiye'de varlığı yeniden kanıtlanan büyük kedi hangisi?",
      options: [{ t: "Çita", i: "🐆", p: "cita" }, { t: "Anadolu Parsı", i: "🐾", p: "anadolu-parsi" }, { t: "Puma", i: "dark:🐈", p: "puma" }], answer: 1,
      fact: "Anadolu parsının Türkiye'de yok olduğu düşünülüyordu. Son yıllarda Akdeniz, Ege, Güneydoğu Anadolu ve Doğu Karadeniz'de fotokapanlarla görüntülenmesi, yaşamaya devam ettiğini kanıtladı." },
    { id: "g-endemik", lv: 4, cat: "doga", type: "choice", q: "Hangisi yalnızca Türkiye'de yaşayan (endemik) bir türdür?",
      options: [{ t: "Bozayı", i: "🐻", p: "bozayi" }, { t: "İnci Kefali", i: "🐟", p: "inci-kefali" }, { t: "Kızıl Tilki", i: "🦊", p: "kizil-tilki" }], answer: 1,
      fact: "İnci kefali dünyada yalnızca Van Gölü havzasında yaşar ve gölün sodalı suyunda yaşayabilen tek balık türüdür." },
    { id: "g-inci-harita", lv: 3, cat: "doga", type: "map", photo: "inci-kefali", q: "İnci kefalini, yaşadığı gölün bulunduğu ilimize sürükle!",
      item: "🐟", label: "İnci Kefali", cities: ["van", "konya", "izmir", "istanbul", "antalya", "samsun"], answer: "van",
      fact: "Her bahar binlerce inci kefali, yumurtlamak için Van Gölü'nden tatlı su derelerine akıntıya karşı yüzer." },
    { id: "g-firat-endemik", lv: 4, cat: "doga", type: "truefalse", photo: "firat-kaplumbagasi", q: "Fırat kaplumbağası yalnızca Türkiye'de yaşayan (endemik) bir türdür.", answer: false,
      fact: "Fırat kaplumbağası Türkiye'nin yanı sıra Suriye, Irak ve İran'daki Fırat-Dicle havzasında da yaşar. Yani Türkiye'ye değil, Fırat-Dicle havzasına endemiktir (özgüdür) ve nesli tehlike altındadır." },
    { id: "g-kelaynak-siluet", lv: 3, cat: "doga", type: "silhouette", photo: "kelaynak", q: "Bu siluet, dünyanın en nadir kuşlarından biri olan hangi türe ait?",
      art: "svg:kelaynak", options: [{ t: "Kelaynak" }, { t: "Leylek" }, { t: "Flamingo" }], answer: 0,
      fact: "Kelaynak, IUCN Kırmızı Listesi'nde 'Tehlikede' (EN) kategorisindedir. Birecik'teki koruma çalışmaları türün yaşaması için çok önemlidir." },
    { id: "g-pati", lv: 3, cat: "doga", type: "silhouette", typeLabel: "İzleri takip et", photo: "anadolu-parsi", q: "Bu iz, Türkiye'de yaşayan hangi yırtıcıya ait olabilir? İpucu: tırnak izi yok!",
      art: "svg:pati", options: [{ t: "Anadolu Parsı" }, { t: "Kurt" }, { t: "Bozayı" }], answer: 0,
      fact: "Pars gibi kedigillerin çoğu yürürken tırnaklarını içeri çeker, bu yüzden izlerinde tırnak görünmez. Hızlı koşan çita ise istisnadır! Kurt ve ayı izlerinde tırnaklar belirgindir." },
    { id: "g-circir", lv: 3, cat: "doga", type: "truefalse", photo: "circir-bocegi", q: "Cırcır böcekleri havalar ısındıkça daha hızlı öter.", answer: true,
      fact: "Cırcır böcekleri sıcak havada daha hızlı öter. Ötüş sayısından havanın sıcaklığı tahmin edilebilir!" },
    { id: "g-karagul", lv: 3, cat: "doga", type: "choice", q: "Halfeti'nin karagülü neden koyu renkte açar?",
      options: [{ t: "Toprağı ve iklimi", i: "🌍" }, { t: "Boyanması", i: "🎨" }, { t: "Geceleri açması", i: "🌙" }], answer: 0,
      fact: "Karagül başka bir yere dikildiğinde zamanla kırmızı açmaya başlar. Bu yüzden Halfeti'ye özgü bir hazinedir." },
    { id: "g-iucn", lv: 4, cat: "doga", type: "choice", q: "IUCN Kırmızı Listesi'nde 'CR' kısaltması ne anlama gelir?",
      options: [{ t: "Kritik tehlikede", i: "🚨" }, { t: "Asgari endişe", i: "✅" }, { t: "Yetersiz veri", i: "❓" }], answer: 0,
      fact: "Kırmızı Liste türleri 'Asgari Endişe'den 'Tükenmiş'e kadar sınıflandırır. CR, türün doğada tükenme riskinin son derece yüksek olduğu anlamına gelir." },
    { id: "g-biyocesitlilik", lv: 4, cat: "doga", type: "truefalse", q: "Türkiye, üç farklı biyocoğrafik bölgenin kesiştiği yerde olduğu için biyoçeşitlilik açısından çok zengindir.", answer: true,
      fact: "Türkiye'de 11 binden fazla bitki türü bulunur ve bunların yaklaşık üçte biri endemiktir." },
    { id: "g-ceylan-siluet", lv: 4, cat: "doga", type: "silhouette", photo: "ceylan", q: "Şanlıurfa'da devlete ait bir tarım işletmesinde (TİGEM) koruma altında çoğaltılan bu tür hangisi?",
      art: "svg:ceylan", options: [{ t: "Ceylan" }, { t: "Yaban keçisi" }, { t: "Karaca" }], answer: 0,
      fact: "Türkiye'nin en büyük Asya ceylanı sürüsü Ceylanpınar Tarım İşletmesi'nde koruma altındadır. 1982'de sadece 23 ceylanla başlayan sürüde bugün yaklaşık bin ceylan yaşıyor." },
    { id: "g-pestisit", lv: 3, cat: "doga", type: "choice", photo: "bal-arisi", q: "Arı gibi tozlaşma yapan canlıların azalmasının en önemli nedenlerinden biri hangisidir?",
      options: [{ t: "Bilinçsiz ilaç kullanımı", i: "🧪" }, { t: "Çiçeklerin çoğalması", i: "🌸" }, { t: "Yağmur yağması", i: "🌧️" }], answer: 0,
      fact: "Tarım ilaçları arılara zarar verebilir. Bu yüzden bitkiler çiçekteyken ilaçlama yapılmamalı; gerekiyorsa arıların uçmadığı akşam saatlerinde ve doğru dozda yapılmalıdır." },
    // ---------- SEVİYE 4 (14 yaş ve üstü) ek sorular ----------
    { id: "u-siirt-fistik", lv: 4, cat: "tarim", type: "map", photo: "antep-fistigi", q: "Antep fıstığından daha iri ve dolgun taneli, coğrafi işaretli fıstığımız adını hangi ilimizden alır? Fıstığı o ile sürükle!",
      item: "svg:fistik", label: "Fıstık", cities: ["siirt", "gaziantep", "erzurum", "samsun", "izmir", "edirne"], answer: "siirt",
      fact: "Siirt fıstığı uzun yıllar Antep fıstığının bir çeşidi sayıldı. 2025'te kendi adıyla coğrafi işaret tescili aldı." },
    { id: "u-hidroponik", lv: 4, cat: "tarim", type: "choice", q: "Topraksız tarımda (hidroponik) bitkiler ihtiyaç duydukları mineralleri nereden alır?",
      options: [{ t: "Besin çözeltili sudan", i: "💧" }, { t: "Kumdan", i: "⏳" }, { t: "Havadaki tozdan", i: "🌬️" }], answer: 0,
      fact: "Hidroponik sistemlerde kökler, gerekli mineralleri içeren suyla beslenir. Su geri kullanılabildiği için daha az su harcanabilir." },
    { id: "u-ikinci-urun", lv: 4, cat: "tarim", type: "choice", q: "Harran Ovası'nda aynı tarladan bir yılda iki ürün alınabilmesini ne sağladı?",
      options: [{ t: "GAP ile gelen sulama", i: "💧" }, { t: "Kar yağışının artması", i: "❄️" }, { t: "Rüzgâr enerjisi", i: "🌬️" }], answer: 0,
      fact: "Sulama sayesinde Harran Ovası'nda buğday hasadından sonra mısır gibi ikinci bir ürün ekilebiliyor." },
    { id: "u-dron", lv: 3, cat: "tarim", type: "truefalse", q: "Tarım dronları tarlayı havadan görüntüleyebilir ama ilaç püskürtemez.", answer: false,
      fact: "Tarım dronları ilaçlama ve gübrelemede, bitki sağlığını izlemede ve rekolte tahmininde de kullanılır." },
    { id: "u-tuzlanma", lv: 4, cat: "tarim", type: "choice", photo: "damla-sulama", q: "Aşağıdakilerden hangisi tarım topraklarında tuzlanmaya yol açabilir?",
      options: [{ t: "Aşırı sulama ve yetersiz drenaj", i: "🚿" }, { t: "Ağaçlandırma", i: "🌳" }, { t: "Nöbetleşe ekim", i: "🔄" }], answer: 0,
      fact: "Sıcak ovalarda fazla su ve yetersiz drenaj, topraktaki tuzun yüzeye çıkmasına neden olabilir. Damla sulama ve drenaj bunu azaltır." },
    { id: "u-birecik-harita", lv: 3, cat: "doga", type: "map", photo: "kelaynak", q: "Kelaynakların korunduğu Birecik ilçesi hangi ilimizdedir? Kelaynağı haritada o şehre sürükle!",
      item: "svg:kelaynak", label: "Kelaynak", cities: ["sanliurfa", "gaziantep", "adana", "malatya", "diyarbakir", "van"], answer: "sanliurfa",
      fact: "Birecik, Şanlıurfa'nın Fırat kıyısındaki ilçesidir. Kelaynaklar burada koruma altında yaşatılıyor." },
    { id: "u-gobeklitepe", lv: 4, cat: "tarim", type: "choice", q: "Tarımın başladığı döneme ışık tutan Göbeklitepe'nin en eski yapıları yaklaşık kaç yıllıktır?",
      options: [{ t: "Yaklaşık 11 bin 600 yıl", i: "🗿" }, { t: "Yaklaşık 2 bin yıl", i: "🏛️" }, { t: "Yaklaşık 500 yıl", i: "🕌" }], answer: 0,
      fact: "Göbeklitepe'nin en eski yapıları MÖ 9600 civarına tarihlenir. 2018'de UNESCO Dünya Mirası Listesi'ne girdi." },
    { id: "u-biyolojik-mucadele", lv: 4, cat: "tarim", type: "choice", photo: "ugur-bocegi", q: "Tarımda 'biyolojik mücadele' ne demektir?",
      options: [{ t: "Zararlılara karşı doğal düşmanlarını kullanmak", i: "🐞" }, { t: "Daha güçlü ilaç kullanmak", i: "🧪" }, { t: "Tarlayı yakmak", i: "🔥" }], answer: 0,
      fact: "Örneğin uğur böcekleri yaprak bitlerini yiyerek bitkileri doğal yoldan korur; böylece ilaç kullanımı azaltılabilir." },
    { id: "u-celtik-metan", lv: 4, cat: "tarim", type: "choice", q: "Su altında tutulan çeltik (pirinç) tarlaları hangi sera gazının önemli kaynaklarındandır?",
      options: [{ t: "Metan", i: "💨" }, { t: "Oksijen", i: "🌬️" }, { t: "Helyum", i: "🎈" }], answer: 0,
      fact: "Su altındaki çeltik tarlalarında oksijensiz ortamda yaşayan mikroorganizmalar metan üretir. Tarlayı aralıklı sulamak bu salımı azaltabilir." },
    { id: "u-ari-renk", lv: 4, cat: "doga", type: "truefalse", photo: "bal-arisi", q: "Bal arıları kırmızı rengi iyi göremez ama morötesi (UV) ışığı görebilir.", answer: true,
      fact: "Arıların gözü mavi, yeşil ve morötesi ışığa duyarlıdır. Çiçeklerdeki, insanın göremediği morötesi desenler arıları nektara yönlendirir." },

    // ---------- YENİ SORULAR (v2.7) ----------
    { id: "n-su-tarim", lv: 3, cat: "tarim", type: "choice", q: "Dünyada kullanılan tatlı suyun en büyük bölümü hangi alanda harcanır?",
      options: [{ t: "Evlerde", i: "🏠" }, { t: "Fabrikalarda", i: "🏭" }, { t: "Tarımsal sulamada", i: "🌾" }], answer: 2,
      fact: "FAO'ya göre dünyada kullanılan tatlı suyun yaklaşık %70'i tarıma gider; Asya ve Afrika'da bu oran %80'i geçer. Bu yüzden damla sulama gibi su tasarrufu sağlayan yöntemler çok önemlidir." },
    { id: "n-ari-dansi", lv: 3, cat: "tarim", type: "choice", photo: "bal-arisi", q: "Bal arıları, buldukları çiçeklerin yerini kovandaki arkadaşlarına nasıl anlatır?",
      options: [{ t: "Renk değiştirerek", i: "🎨" }, { t: "Dans ederek", i: "💃" }, { t: "Işık yakıp söndürerek", i: "💡" }], answer: 1,
      fact: "Dansın yönü çiçeğin güneşe göre yönünü, süresi ise uzaklığını anlatır. Arıların bu 'dilini' çözen Karl von Frisch, 1973'te Nobel Ödülü aldı." },
    { id: "n-genbank-harita", lv: 3, cat: "tarim", type: "map", photo: "yerel-tohum", q: "TAGEM'e bağlı Türkiye Tohum Gen Bankası hangi ilimizde? Tohumu oraya sürükle!",
      item: "🌱", label: "Tohum", cities: ["ankara", "sanliurfa", "van", "antalya", "edirne", "rize"], answer: "ankara",
      fact: "Türkiye'nin ilk tohum gen bankası 1964'te İzmir'de kuruldu. Ankara'daki Türkiye Tohum Gen Bankası 2010'da açıldı ve en çok tahıl tohumlarını saklar." },
    { id: "n-endemik-harran", lv: 3, cat: "doga", type: "choice", photo: "e-harrankeleri", q: "Harran yaprakparmaklı keleri gibi, dünyada yalnızca belirli bir bölgede yaşayan türlere ne denir?",
      options: [{ t: "Göçmen tür", i: "🧭" }, { t: "İstilacı tür", i: "⚠️" }, { t: "Endemik tür", i: "📍" }], answer: 2,
      fact: "Adındaki 'yaprakparmaklı', parmak uçlarındaki yaprak biçimli tutunma yastıklarından gelir. Bu küçük keler, dünyada yalnızca Güneydoğu Anadolu'da yaşar." },
    { id: "n-flamingo-renk", lv: 3, cat: "doga", type: "truefalse", q: "Flamingolar pembe rengini, yedikleri alg ve minik kabuklulardaki renk maddelerinden alır.", answer: true,
      fact: "Flamingo yavruları gri tüylü olarak yumurtadan çıkar; pembeleşmeleri 2-3 yıl sürer. Türkiye'de flamingoların en önemli üreme alanı Tuz Gölü'dür." },
    { id: "n-yarasa-siluet", lv: 3, cat: "doga", type: "silhouette", q: "Bu siluet, karanlıkta seslerin yankısıyla yön bulan hangi hayvana ait?",
      art: "🦇", options: [{ t: "Baykuş" }, { t: "Yarasa" }, { t: "Kırlangıç" }], answer: 1,
      fact: "Yarasalar gerçekten uçabilen tek memelilerdir ve hiçbiri kör değildir. Türkiye'deki yarasaların çoğu böcek yer; tarım zararlılarını azaltarak çiftçiye yardım eder." },
    { id: "n-pamuk-lif", lv: 4, cat: "tarim", type: "choice", photo: "pamuk", q: "Harran Ovası'nın 'beyaz altını' pamuğun lifleri, bitkinin neresinde oluşur?",
      options: [{ t: "Tohumun kabuğunda", i: "🌰" }, { t: "Taç yapraklarında", i: "🌸" }, { t: "Yapraklarında", i: "🍃" }], answer: 0,
      fact: "Her pamuk lifi, tohum kabuğundaki tek bir hücrenin uzamasıyla oluşur. Birkaç santimetreye ulaşan bu lifler, bitkilerdeki en uzun hücrelerdendir!" },
    { id: "n-bereketli-hilal", lv: 4, cat: "tarim", type: "choice", q: "Şanlıurfa'nın da içinde yer aldığı, tarımın ilk başladığı bölgelerden birine ne ad verilir?",
      options: [{ t: "İpek Yolu", i: "🐫" }, { t: "Amazon Havzası", i: "🌳" }, { t: "Bereketli Hilal", i: "🌙" }], answer: 2,
      fact: "Bölge adını haritadaki hilal biçiminden alır. Buğday, arpa, mercimek ve nohudun yabani ataları, bugün de Güneydoğu Anadolu'da doğal olarak yetişir." },
    { id: "n-insitu-ceylanpinar", lv: 4, cat: "tarim", type: "choice", q: "Yabani buğday akrabalarının Ceylanpınar'da doğal ortamlarında korunması hangi yönteme örnektir?",
      options: [{ t: "Gen bankasında (ex situ) koruma", i: "❄️" }, { t: "Yerinde (in situ) koruma", i: "🏞️" }, { t: "Biyolojik mücadele", i: "🐞" }], answer: 1,
      fact: "1990'larda Ceylanpınar Tarım İşletmesi'nde buğdayın 5 yabani akrabası için gen koruma alanları seçildi. Doğada korunan bitkiler değişen koşullara uyum sağlamayı sürdürür." },
    { id: "n-mercimek-azot", lv: 4, cat: "tarim", type: "truefalse", q: "Mercimek gibi baklagiller, köklerindeki bakteriler sayesinde havadaki azottan yararlanabilir.", answer: true,
      fact: "Bu yüzden ekim nöbetine katılan baklagiller toprağı zenginleştirip gübre ihtiyacını azaltır. Türkiye'nin kırmızı mercimeği ağırlıklı olarak Güneydoğu Anadolu'da yetişir." },
    { id: "n-aniz-yakma", lv: 4, cat: "tarim", type: "truefalse", q: "Hasattan sonra tarladaki anızı (sap artıklarını) yakmak toprağın verimini artırır.", answer: false,
      fact: "Anız yakmak topraktaki organik maddeyi ve faydalı canlıları yok eder, toprağı erozyona açık bırakır, yangınlara yol açabilir. Bu yüzden yasaktır; anız toprağa karıştırılmalıdır." },
    { id: "n-likya-semenderi", lv: 4, cat: "doga", type: "choice", photo: "e-likyasemenderi", q: "Türkiye'ye endemik Antalya Likya semenderi hangi hayvan grubundandır?",
      options: [{ t: "İki yaşamlılar (amfibiler)", i: "🐸" }, { t: "Sürüngenler", i: "🦎" }, { t: "Balıklar", i: "🐟" }], answer: 0,
      fact: "Likya semenderleri yumurta bırakmaz; dişiler genellikle yalnızca iki yavru doğurur. Nemli kireçtaşı kayalıklarda yaşayan bu türün nesli tehlike altındadır." },
    { id: "n-ramsar", lv: 4, cat: "doga", type: "choice", q: "Sulak alanları ve su kuşlarını korumak için imzalanan uluslararası sözleşme hangisidir?",
      options: [{ t: "Kyoto Protokolü", i: "🏭" }, { t: "Montreal Protokolü", i: "🌐" }, { t: "Ramsar Sözleşmesi", i: "🦆" }], answer: 2,
      fact: "Sözleşme adını 1971'de imzalandığı İran'daki Ramsar kentinden alır. Türkiye 1994'te taraf oldu; Sultan Sazlığı ve Kızılırmak Deltası Ramsar alanlarımızdandır." },
    { id: "n-yaban-koyunu-harita", lv: 4, cat: "doga", type: "map", photo: "e-yabankoyunu", q: "Endemik Anadolu yaban koyununun son doğal sürüsü hangi ilimizde korundu? Koyunu oraya sürükle!",
      item: "🐏", label: "Yaban Koyunu", cities: ["konya", "rize", "izmir", "erzurum", "edirne", "samsun"], answer: "konya",
      fact: "1960'larda yalnızca Konya Bozdağ'da 40-50 hayvan kalmıştı. 1969'dan beri korunan bu sürüden Ankara, Karaman ve Aksaray gibi illere hayvan taşınarak yeni sürüler kuruldu." },
    // ---------- YENİ SORULAR (v3.2) ----------
    { id: "v3-celtik-harita", lv: 3, cat: "tarim", type: "map", q: "Türkiye'de en çok çeltik (pirinç) yetiştiren ilimize pirinci sürükle!",
      item: "🍚", label: "Pirinç", cities: ["edirne", "van", "erzurum", "gaziantep", "antalya", "kayseri"], answer: "edirne",
      fact: "Edirne'nin Meriç ve İpsala ovalarındaki çeltik, su altında tutulan tarlalarda büyür. Edirne'deki TAGEM'e bağlı Trakya Tarımsal Araştırma Enstitüsü yeni çeltik çeşitleri geliştirir." },
    { id: "v3-finike-harita", lv: 3, cat: "tarim", type: "map", q: "Coğrafi işaretli Finike portakalı hangi ilimizde yetişir? Portakalı oraya sürükle!",
      item: "🍊", label: "Portakal", cities: ["antalya", "erzurum", "samsun", "ankara", "van", "edirne"], answer: "antalya",
      fact: "Portakal ağaçları soğuğa dayanamaz; bu yüzden turunçgiller en çok ılık Akdeniz kıyılarında yetişir. Finike portakalı ince kabuğu ve bol suyuyla ünlüdür." },
    { id: "v3-yanardoner-harita", lv: 3, cat: "doga", type: "map", photo: "e-yanardoner", q: "Endemik yanardöner çiçeği dünyada yalnızca hangi ilimizde doğal olarak yetişir? Çiçeği oraya sürükle!",
      item: "🌸", label: "Yanardöner", cities: ["ankara", "rize", "izmir", "diyarbakir", "van", "adana"], answer: "ankara",
      fact: "Yanardöner yalnızca Ankara'nın Gölbaşı çevresinde doğal olarak yetişir ve kırmızı-pembe çiçekler açar. Yaşadığı alanların yapılaşması onu tehdit ediyor." },
    { id: "v3-kirpikli-zambak", lv: 3, cat: "doga", type: "choice", photo: "e-kirpikli-zambak", q: "Endemik kirpikli zambak dünyada yalnızca hangi bölgemizin dağlarında yetişir?",
      options: [{ t: "Doğu Karadeniz", i: "🏔️" }, { t: "Trakya", i: "🌻" }, { t: "Ege kıyıları", i: "🏖️" }], answer: 0,
      fact: "Kirpikli zambak, Doğu Karadeniz dağlarında 1500-2400 metre yükseklikte, yazın açar. Dünyanın başka hiçbir yerinde doğal olarak yetişmez." },
    { id: "v3-akrep-siluet", lv: 3, cat: "doga", type: "silhouette", q: "Bu siluet, Göbeklitepe'nin dikili taşlarına da oyulmuş hangi hayvana ait?",
      art: "🦂", options: [{ t: "Yengeç" }, { t: "Akrep" }, { t: "Karınca" }], answer: 1,
      fact: "Akrepler kuyruklarının ucundaki iğneyle avlanır ve korunur; morötesi ışıkta parlarlar! Göbeklitepe'deki 43 numaralı dikili taşta da bir akrep kabartması vardır." },
    { id: "v3-ekim-nobeti", lv: 3, cat: "tarim", type: "truefalse", q: "Tarlaya her yıl farklı ürün ekmek (ekim nöbeti), toprağı korur ve bitki hastalıklarını azaltır.", answer: true,
      fact: "Aynı ürünü hep aynı tarlaya ekmek toprağı yorar, o bitkinin zararlılarını da çoğaltır. Buğdaydan sonra nohut ya da mercimek ekmek toprağa azot kazandırır." },
    { id: "v3-agac-halka", lv: 3, cat: "doga", type: "truefalse", q: "Kesilmiş bir ağacın yaşı, gövdesindeki halkalar sayılarak bulunabilir.", answer: true,
      fact: "Ağaç her yıl yeni bir halka ekler. Yağışlı yıllarda halkalar geniş, kurak yıllarda dar olur; bilim insanları geçmişin iklimini bu halkalardan okur." },
    { id: "v3-ana-ari", lv: 3, cat: "tarim", type: "choice", photo: "bal-arisi", q: "Bir bal arısı kovanında yumurtlayan arı hangisidir?",
      options: [{ t: "Ana arı", i: "👑" }, { t: "İşçi arı", i: "🛠️" }, { t: "Erkek arı", i: "🐝" }], answer: 0,
      fact: "Ana arı yaz aylarında günde 1.500-2.000 yumurta bırakabilir. Kovandaki bütün işçi arılar dişidir; erkek arıların ise iğnesi yoktur." },
    { id: "v3-erozyon", lv: 3, cat: "tarim", type: "choice", q: "Verimli toprağın rüzgâr ve yağmur suyuyla taşınıp kaybolmasına ne ad verilir?",
      options: [{ t: "Fotosentez", i: "🌿" }, { t: "Erozyon", i: "🏜️" }, { t: "Buharlaşma", i: "♨️" }], answer: 1,
      fact: "Bitkiler kökleriyle toprağı tutar. Eğimli tarlalarda eğime dik sürmek, teras yapmak ve ağaçlandırma erozyonu azaltır." },
    { id: "v3-kus-goc-yolu", lv: 3, cat: "doga", type: "choice", q: "Leylekler ve yırtıcı kuşlar göç ederken büyük sürüler hâlinde hangi yerin üzerinden geçer?",
      options: [{ t: "İstanbul Boğazı", i: "🌉" }, { t: "Van Gölü", i: "🏞️" }, { t: "Kapadokya", i: "🎈" }], answer: 0,
      fact: "Süzülen kuşlar sıcak hava akımlarıyla yükselir ve uzun deniz geçişlerinden kaçınır; bu yüzden karaların en yakın olduğu Boğaz'dan geçerler. Hatay'daki Belen Geçidi de önemli bir göç yoludur." },
    { id: "v3-nesli-tukenme", lv: 3, cat: "doga", type: "choice", q: "Bir canlının 'neslinin tükenmesi' ne demektir?",
      options: [{ t: "O türden hiç birey kalmaması", i: "❌" }, { t: "Başka bir yere göç etmesi", i: "🧭" }, { t: "Kış uykusuna yatması", i: "💤" }], answer: 0,
      fact: "Hazar kaplanı bir zamanlar Anadolu'da da yaşardı; bugün dünyada hiç kalmadı. Kelaynak gibi türleri koruma çalışmaları, onların aynı sonu yaşamaması için yapılır." },
    { id: "v3-sera", lv: 3, cat: "tarim", type: "choice", q: "Seralar, bitkilere en çok hangi konuda yardım eder?",
      options: [{ t: "Soğukta sıcak ortam sağlar", i: "🌡️" }, { t: "Bitkileri karanlıkta tutar", i: "🌑" }, { t: "Yağmur suyunu biriktirir", i: "🌧️" }], answer: 0,
      fact: "Sera, güneş ışığını içeri alıp ısıyı tutar; böylece kışın da domates, biber ve salatalık yetişir. Ülkemizde seraların en çok olduğu il Antalya'dır." },
    { id: "v3-biyomucadele-harita", lv: 4, cat: "tarim", type: "map", photo: "ugur-bocegi", q: "TAGEM'e bağlı Biyolojik Mücadele Araştırma Enstitüsü hangi ilimizde? Uğur böceğini oraya sürükle!",
      item: "🐞", label: "Uğur Böceği", cities: ["adana", "erzurum", "samsun", "izmir", "van", "ankara"], answer: "adana",
      fact: "Enstitü, zararlılara karşı ilaç yerine onların doğal düşmanlarını araştırır ve çoğaltır. Böylece hem doğa hem de sofralarımız daha az ilaçla karşılaşır." },
    { id: "v3-sultan-sazligi-harita", lv: 4, cat: "doga", type: "map", q: "Ramsar Sözleşmesi ile korunan kuş cenneti Sultan Sazlığı hangi ilimizde? Kuşu oraya sürükle!",
      item: "🦆", label: "Su Kuşu", cities: ["kayseri", "izmir", "trabzon", "van", "edirne", "sanliurfa"], answer: "kayseri",
      fact: "Sultan Sazlığı'nda 300 kadar kuş türü kaydedilmiştir. Tatlı ve tuzlu suyun bir arada bulunduğu bu sulak alanda flamingolar da kuluçkaya yatar." },
    { id: "v3-kasnak-harita", lv: 4, cat: "doga", type: "map", photo: "e-kasnak-mesesi", q: "Endemik kasnak meşesi, adını taşıyan bir koruma alanıyla hangi ilimizde korunur? Meşeyi oraya sürükle!",
      item: "🌳", label: "Kasnak Meşesi", cities: ["isparta", "trabzon", "erzurum", "van", "samsun", "diyarbakir"], answer: "isparta",
      fact: "Kasnak meşesi dünyada yalnızca Anadolu'da yetişir ve boyu 30 metreyi bulabilir. Eğirdir'deki Kasnak Meşesi Tabiat Koruma Alanı onun en bilinen yaşam alanıdır." },
    { id: "v3-kazdagi-goknari", lv: 4, cat: "doga", type: "choice", photo: "e-kazdagi-goknari", q: "Kazdağı göknarının bilimsel adındaki 'equi-trojani' ne anlama gelir?",
      options: [{ t: "Truva atı", i: "🐴" }, { t: "Dağ kartalı", i: "🦅" }, { t: "Kuzey rüzgârı", i: "🌬️" }], answer: 0,
      fact: "Efsaneye göre Truva atı bu göknarın odunundan yapıldı. Kazdağı göknarı dünyada yalnızca Kaz Dağları'nda doğal olarak yetişir." },
    { id: "v3-islah", lv: 4, cat: "tarim", type: "choice", q: "Tarımda 'bitki ıslahı' ne demektir?",
      options: [{ t: "İstenen özellikte yeni çeşit geliştirmek", i: "🧬" }, { t: "Bitkileri ilaçlamak", i: "🧴" }, { t: "Toprağı sürmek", i: "🚜" }], answer: 0,
      fact: "TAGEM'e bağlı enstitüler kuraklığa ve hastalıklara dayanıklı buğday, nohut ve mercimek çeşitleri geliştirir. Yeni bir çeşidin geliştirilmesi çoğu zaman 10 yıldan uzun sürer." },
    { id: "v3-gida-israfi", lv: 4, cat: "tarim", type: "choice", q: "FAO'ya göre dünyada üretilen gıdanın yaklaşık ne kadarı kaybediliyor ya da israf ediliyor?",
      options: [{ t: "Yüzde biri", i: "🥄" }, { t: "Yaklaşık üçte biri", i: "🍽️" }, { t: "Neredeyse tamamı", i: "🗑️" }], answer: 1,
      fact: "Bakanlığımızın 'Gıdanı Koru, Sofrana Sahip Çık' kampanyası israfı azaltmayı hedefler. Tabağına yiyebileceğin kadar almak da israfı önler!" },
    { id: "v3-endemik-oran", lv: 4, cat: "doga", type: "choice", q: "Türkiye'deki bitki türlerinin yaklaşık ne kadarı yalnızca Türkiye'de yetişir (endemiktir)?",
      options: [{ t: "Yaklaşık üçte biri", i: "🌿" }, { t: "Yüzde biri", i: "🌱" }, { t: "Hepsi", i: "🌳" }], answer: 0,
      fact: "Ülkemizde 12.000'e yakın bitki türü yetişir; bunların yaklaşık üçte biri dünyada başka hiçbir yerde doğal olarak yoktur." },
    { id: "v3-cografi-isaret", lv: 4, cat: "tarim", type: "truefalse", photo: "antep-fistigi", q: "Coğrafi işaret, bir ürünün ünlü özelliklerini yetiştiği yöreden aldığını gösteren resmî bir tescildir.", answer: true,
      fact: "Ülkemizde 1.000'den fazla ürün coğrafi işaretle tescillidir. Antep fıstığı, Malatya kayısısı ve Aydın inciri bunlardan yalnızca birkaçıdır." },
    { id: "v3-istilaci-tur", lv: 4, cat: "doga", type: "truefalse", q: "Başka bölgelerden gelen istilacı türler, yeni yerlerindeki yerli türleri tehdit edebilir.", answer: true,
      fact: "Süveyş Kanalı'ndan Akdeniz'e geçen aslan balığı kıyılarımızda hızla çoğalıyor ve yerli balıkların yavrularını yiyor. İstilacı türlerin yayılmasını önlemek bu yüzden çok önemli." },
    { id: "v3-kumlu-toprak", lv: 4, cat: "tarim", type: "truefalse", q: "Bitkiler için en verimli toprak, tamamen kumdan oluşan topraktır.", answer: false,
      fact: "Kum suyu tutamaz, kil ise fazla su tutup havasız kalır. En verimlisi kum, kil ve çürümüş bitki artıklarının (humus) dengeli karıştığı tınlı topraktır." },
    { id: "v3-geyik-siluet", lv: 4, cat: "doga", type: "silhouette", q: "Bu siluet, erkeklerinin her yıl boynuzunu döküp yeniden çıkardığı hangi hayvana ait?",
      art: "🦌", options: [{ t: "Dağ keçisi" }, { t: "Geyik" }, { t: "Yaban koyunu" }], answer: 1,
      fact: "Geyik boynuzları kemiktendir ve her yıl yeniden çıkar; keçi ve koyunun boynuzları ise ömür boyu kalır. Alageyiğin ülkemizdeki son doğal topluluğu Antalya Düzlerçamı'nda korunur." }
  ]
};
